### ISSUE TITLE
Cell-locator build fails on Ubuntu 20 due to Python shared library linker errors.

### ISSUE THREAD

**Issue by allemangD** [BICCN/cell-locator#125]
**Environment**

* OS: Ubuntu 20.04

The same issue occurs using both Unix Makefiles and Ninja generators. I've installed the python build dependency packages via `apt build-dep python2.7 python3.8`, but I'm unsure if that's relevant.

**Description**
Following the basic build directions in `BUILD.md`, Python shared library compilation fails, causing some linker errors. Specific errors are:

```
[ 24%] Performing build step for 'python'
...
[ 97%] Linking C executable ../../bin/python
Creating 'bin/./Modules/Setup.local'
/usr/bin/ld: ../../lib/libpython2.7.so: undefined reference to `minor'
/usr/bin/ld: ../../lib/libpython2.7.so: undefined reference to `major'
/usr/bin/ld: ../../lib/libpython2.7.so: undefined reference to `makedev'
collect2: error: ld returned 1 exit status
make[5]: *** [CMakeBuild/python/CMakeFiles/python.dir/build.make:95: bin/python] Error 1
make[4]: *** [CMakeFiles/Makefile2:3731: CMakeBuild/python/CMakeFiles/python.dir/all] Error 2
make[3]: *** [Makefile:144: all] Error 2
make[2]: *** [slicersources-build/CMakeFiles/python.dir/build.make:122: slicersources-build/python-prefix/src/python-stamp/python-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:540: slicersources-build/CMakeFiles/python.dir/all] Error 2
make: *** [Makefile:87: all] Error 2
```

This seems the same as the issue and fix mentioned [on the Slicer discourse](https://discourse.slicer.org/t/build-error-libpython2-7-so-undefined-reference-to-minor/6470/2). @jcfr mentions a workaround there involving python-cmake-buildsystem, but I'm unsure so far how to apply that workaround to cell-locator. That discussion thread also indicates the same issue would occur on Ubuntu 18, although I haven't tried this.

**How to Reproduce**
```
git clone git@github.com:BICCN/cell-locator.git
mkdir cell-locator-build
cd cell-locator-build
cmake -G 'Unix Makefiles' ../cell-locator
make
```

**Comment by jcfr** [comment]
Thanks for the detailed report :pray: 

> I've installed the python build dependency packages via apt build-dep python2.7 python3.8

Since _Slicer build system_ builds and packages its own python interpreter, there is no need to install python to support the build.

## Description of problem

It turns out that Slicer version built by cell-locator is Python 2.7.13 and version https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/commit/c3b8d532242efed85fb3cd77b0e39e424b6db475 of the build system is used. See https://github.com/KitwareMedical/Slicer/blob/cell-locator-v4.11.0-2018-12-19-0dc589ee5/SuperBuild/External_python.cmake#L56-L60

## Proposed solution

Backport https://github.com/Slicer/Slicer/commit/963f1def3eb8d2913ee755b9f07ee7572505e04c#diff-b5113bba46ccfe591cd43216cab396f9

### Analysis

> undefined reference to `minor|major|makedev'

At first, I tried to reproduce the python build error using the dockbuild/dockbuild/ubuntu2004 image and I wasn't able to.
(To find out how to use the image, see https://github.com/Slicer/Slicer/issues/5005#issuecomment-648932268)

Here is what I did:

```
mkdir /tmp/cell-locator-issue-125
cd  /tmp/cell-locator-issue-125

dockbuild-ubuntu2004 bash
```

Then

```
git clone https://github.com/python-cmake-buildsystem/python-cmake-buildsystem
mkdir build
cd build
cmake -DPYTHON_VERSION:STRING=2.7.15 and -DBUILD_LIBPYTHON_SHARED:BOOL=1 ../python-cmake-buildsystem/
make -j5
```

After using the same version of python and python-cmake-buildsystem used in the Slicer version used in cell-locator, I was able to reproduce the issue:

```
cd /work/python-cmake-buildsystem
git ckeckout c3b8d532242efed85fb3cd77b0e39e424b6db475
cd ..
rm -rf build
mkdir build
cd build
cmake -DPYTHON_VERSION:STRING=2.7.13 and -DBUILD_LIBPYTHON_SHARED:BOOL=1 ../python-cmake-buildsystem
make -j5
[...]
/usr/bin/ld: ../../lib/libpython2.7.so: undefined reference to `minor'
/usr/bin/ld: ../../lib/libpython2.7.so: undefined reference to `major'
/usr/bin/ld: ../../lib/libpython2.7.so: undefined reference to `makedev'
```

**Comment by jcfr** [comment]
@allemangD  Could you try to build this branch ?

**Comment by allemangD** [comment]
The Python portion of the build now succeeds without issue, but there are new failures as the version of ITK being used does not seem to support gcc 9. I think a sufficient workaround for now will be to use `dockbuild/ubuntu1904-gcc8` or similar with an older gcc.

**Comment by jcfr** [comment]
> The Python portion of the build now succeeds without issue

Great

> new failures as the version of ITK

Can you create a dedicated issue ? 

Can you select gcc8 after running `sudo update-alternatives --config gcc` ?

**Comment by jcfr** [comment]
> I think a sufficient workaround for now will be to use dockbuild/ubuntu1904-gcc8

While building may work, running the application on the host (without creating a package) would assume the path to Qt5 libraries et all all matches.

Would make more sense to use `slicer/buildenv-qt5-centos7:slicer-4.10` from https://github.com/Slicer/SlicerBuildEnvironment/ but even with this one, the development experience will not be pleasant.
